### ISSUE TITLE
Crash on 1.20

### ISSUE THREAD

**Issue by Rozbiynk** [gliscowo/ok-boomer#5]
Game crashes when i try to scroll in resourcepack list
https://mclo.gs/WklyWVu

**Comment by gliscowo** [comment]
Can you reproduce this problem with Ok Boomer only? I haven't been able to make this happen in my development environment and it seems to be a compatibility problem.

If you can't reproduce the issue with the mod alone, it'd be great if you can try to figure out which other mod is causing it happen
Cheers

**Comment by Rozbiynk** [comment]
it was ok zoomer, xd, sorry

**Comment by Rozbiynk** [comment]
After some of bytecoding seems it tweakermore https://mclo.gs/iKJqr5w

**Comment by Rozbiynk** [comment]
hmmm, im try to reproduce it with only these mod but it doesnt work

**Comment by Rozbiynk** [comment]
i think it only redirect mixins from other mod

**Comment by Rozbiynk** [comment]
okay, after some test i can say that is it replay mod

**Comment by Rozbiynk** [comment]
if ok boomer get higher index that replay mod it will be crash when i scroll my mouse wheel

**Comment by Rozbiynk** [comment]
bump

**Comment by Rozbiynk** [comment]
oh

**Comment by gliscowo** [comment]
If you have indeed isolated it to ReplayMod, I need a log where this crash occurs with only ReplayMod installed to know where to look when debugging

**Comment by Rozbiynk** [comment]
okay, ill try to do it

**Comment by Rozbiynk** [comment]
https://mclo.gs/E9Gwk3A

**Comment by KlashRaick** [comment]
[message (1).txt](https://github.com/wisp-forest/ok-boomer/files/12385699/message.1.txt)
